# Chnage the name of this file to DOCKERFILE. Then delete this line.
# run using `docker build --tag python-docker .`
# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster
MAINTAINER Atharva Gundawar <atharva.n.gundawar@gmail.com>

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]